### ISSUE TITLE
Hello Chris, does minwinsdk.exe have the function of uninstall？

### ISSUE THREAD

**Issue by Curious-r** [ChrisDenton/minwinsdk#2]

**Comment by ChrisDenton** [comment]
Hi!

There's no uninstaller yet so [I created one](https://github.com/ChrisDenton/minwinsdk/releases/tag/0.0.1u). I'm in the midsts of rewriting the installer so it's a bit more integrated (and hopefully much improved). That should make a separate uninstaller obsolete.

Alternatively you can manually remove it. The `MIN_WIN_SDK` environment variable gives the directory where it was installer. The directory can be removed as well as the environment variable. Lastly there's the `LIB` environment variable, which you can edit to remove the SDK path or else remove completely if it's the only path there. Btw, in case you aren't aware, there should be a start menu entry for "Edit environment variables for your account" which can be used to edit/remove variables.

**Comment by Curious-r** [comment]
Got it, thank you for reply😎
